nome = str(input('Digite seu nome completo: ')).title().strip()
lista = nome.split()
tamanho = len(lista)
print(nome.title())
print('Primeiro nome: {}'.format(lista[0]))
print('Último nome: {}'.format(lista[tamanho - 1]))
